const char* usage =
"Usage: template [OPTION]... [FILE]...\n"
"\n"
"OPTIONS:\n"
"\n"
"  --version     version info\n"
"  --help        this message\n"
"  --log         log config\n"
"\n"
"Examples:\n"
"\n"
"  template\n"
"\n"
"Source located at https://github.com/jinfeng-zhuang/zstack\n"
"Copyright @ 2021, Jinfeng Zhuang\n";