const char* usage =
"Usage: Win32Ctrl [OPTION]... [FILE]...\n"
"\n"
"OPTIONS:\n"
"\n"
"  --version     version info\n"
"  --help        this message\n"
"  --log         log config\n"
"  --class       \n"
"\n"
"Examples:\n"
"  Win32Ctrl --log \"app:5\"\n"
"  Win32Ctrl --class=\"ComboBoxDemo\"\n"
"\n"
"Supported:\n"
"  SysListView32Demo, ButtonDemo, ComboBoxDemo, GroupBoxDemo, IPDemo, ListBoxDemo, PictureCtrlDemo, ScrollBarDemo, SliderDemo, StaticDemo, TreeViewDemo\n"
"\n"
"Source located at https://github.com/jinfeng-zhuang/zstack\n"
"Copyright @ 2021, Jinfeng Zhuang\n";