#ifndef CARD_ATTR_H
#define CARD_ATTR_H

#include "card_attr_type.h"

enum {
  CARD_ATTR_COST,

  CARD_ATTR_TYPE,

  CARD_ATTR_BLOOD,
  CARD_ATTR_BLOOD_ORIGIN,
  CARD_ATTR_BLOOD_ENHENCE,
  CARD_ATTR_BLOOD_INCREASE,
  CARD_ATTR_BLOOD_DECREASE,
  CARD_ATTR_BLODD_FORCE,

  CARD_ATTR_ATTACK,
  CARD_ATTR_ATTACK_ORIGIN,
  CARD_ATTR_ATTACK_ENHENCE,
};

#endif
