const char *usage =
    "Usage: glib_string [OPTION]... [FILE]...\n"
    "\n"
    "OPTIONS:\n"
    "\n"
    "  --version     version info\n"
    "  --help        this message\n"
    "  --log         log config\n"
    "\n"
    "Examples:\n"
    "\n"
    "  glib_string\n"
    "\n"
    "Source located at https://github.com/jinfeng-zhuang/zstack\n"
    "Copyright @ 2021, Jinfeng Zhuang\n";